package com.resume.backend.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.jsoup.Jsoup;
import org.jsoup.safety.Safelist;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.*;

@Service
public class CloneTemplateService {

    @Value("${gemini.api.key}")
    private String apiKey;

    @Value("${gemini.api.url}")
    private String apiUrl;

    private final RestTemplate restTemplate = new RestTemplate();
    private final ObjectMapper objectMapper = new ObjectMapper();

    public Map<String, Object> cloneDesign(MultipartFile file) throws IOException {
        String url = apiUrl + "?key=" + apiKey;
        String base64Data = Base64.getEncoder().encodeToString(file.getBytes());
        String mimeType = file.getContentType();

        // The architectural prompt: Forcing UI generation and placeholders
        String systemPrompt = "You are an expert frontend developer and UI/UX designer. " +
                "Analyze the visual layout, typography, and colors of the provided resume image. " +
                "Recreate this exact design using standard HTML and inline CSS. " +
                "Do NOT use external stylesheets. " +
                "Use exact placeholders for the data: {{fullName}}, {{email}}, {{phone}}, {{linkedInUrl}}, {{githubUrl}}, {{skills}}. " +
                "For lists like experience and education, create a visually accurate sample block using generic placeholders like {{company}}, {{role}}, {{institution}}, etc. " +
                "Return exactly ONE JSON object matching this schema. Do not wrap in markdown.\n" +
                "{\n" +
                "  \"name\": \"A creative name for this template layout\",\n" +
                "  \"domains\": [\"Industry 1\", \"Industry 2\"],\n" +
                "  \"html\": \"<div style='...'>Your generated HTML code here</div>\"\n" +
                "}";

        Map<String, Object> payload = new HashMap<>();
        Map<String, Object> textPart = new HashMap<>();
        textPart.put("text", systemPrompt);

        Map<String, Object> filePart = new HashMap<>();
        Map<String, String> inlineData = new HashMap<>();
        inlineData.put("mimeType", mimeType);
        inlineData.put("data", base64Data);
        filePart.put("inlineData", inlineData);

        Map<String, Object> partsMap = new HashMap<>();
        partsMap.put("parts", Arrays.asList(textPart, filePart));
        payload.put("contents", Collections.singletonList(partsMap));

        Map<String, Object> generationConfig = new HashMap<>();
        generationConfig.put("responseMimeType", "application/json");
        payload.put("generationConfig", generationConfig);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<Map<String, Object>> entity = new HttpEntity<>(payload, headers);

        try {
            ResponseEntity<String> response = restTemplate.postForEntity(url, entity, String.class);
            return processAndSanitizeResponse(response.getBody());
        } catch (Exception e) {
            throw new RuntimeException("AI Design Cloning failed: " + e.getMessage());
        }
    }

    private Map<String, Object> processAndSanitizeResponse(String responseBody) throws Exception {
        // Navigate Gemini's outer JSON wrapper
        JsonNode rootNode = objectMapper.readTree(responseBody);
        String rawContent = rootNode.path("candidates").get(0)
                .path("content").path("parts").get(0)
                .path("text").asText();

        // Parse the inner JSON generated by our specific prompt
        Map<String, Object> generatedData = objectMapper.readValue(rawContent, Map.class);
        String rawHtml = (String) generatedData.get("html");

        // THE BOUNCER: Sanitize the HTML
        // Use a relaxed list but strictly allow inline styles for design layout
        Safelist customSafelist = Safelist.relaxed()
                .addAttributes(":all", "style", "class", "id");

        String sanitizedHtml = Jsoup.clean(rawHtml, customSafelist);

        // Update the payload with the clean, unbreakable HTML
        generatedData.put("html", sanitizedHtml);

        return generatedData;
    }
}