package com.resume.backend.controller;

import com.resume.backend.service.AtsScoringService;
import com.resume.backend.service.CoverLetterService;
import com.resume.backend.service.InterviewPrepService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/ats")
public class AtsController {

    @Autowired
    private AtsScoringService atsScoringService;
    @Autowired
    private CoverLetterService coverLetterService;

    @PostMapping("/analyze")
    public ResponseEntity<?> analyzeResume(@RequestBody Map<String, String> payload) {
        String resumeJson = payload.get("resumeData");
        String jobDescription = payload.get("jobDescription");

        if (resumeJson == null || jobDescription == null) {
            return ResponseEntity.badRequest().body(Map.of("error", "Both resumeData and jobDescription are required."));
        }

        // We return the raw JSON string generated by Gemini directly to the frontend
        String analysisResultJson = atsScoringService.generateAtsScore(resumeJson, jobDescription);

        return ResponseEntity.ok(analysisResultJson);
    }

    @PostMapping("/cover-letter")
    public ResponseEntity<?> generateCoverLetter(@RequestBody Map<String, String> payload) {
        String resumeJson = payload.get("resumeData");
        String jobDescription = payload.get("jobDescription");

        if (resumeJson == null || jobDescription == null) {
            return ResponseEntity.badRequest().body(Map.of("error", "Missing data"));
        }

        String coverLetterJson = coverLetterService.generateCoverLetter(resumeJson, jobDescription);
        return ResponseEntity.ok(coverLetterJson);
    }

    @Autowired
    private InterviewPrepService interviewPrepService;

    @PostMapping("/interview-prep")
    public ResponseEntity<?> generateInterviewPrep(@RequestBody Map<String, String> payload) {
        String resumeJson = payload.get("resumeData");
        String jobDescription = payload.get("jobDescription");

        if (resumeJson == null || jobDescription == null) {
            return ResponseEntity.badRequest().body(Map.of("error", "Missing resumeData or jobDescription"));
        }

        try {
            // Returns the raw JSON object containing the "qnaList" array
            String prepDataJson = interviewPrepService.generateInterviewPrep(resumeJson, jobDescription);
            return ResponseEntity.ok(prepDataJson);
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("error", e.getMessage()));
        }
    }
}